apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apacheweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apacheweb
  template:
    metadata:
      labels:
        app: apacheweb
    spec:
      containers:
      - name: php-apacheweb
        image: vipin2411/php:7.2-apache-mysqli
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gitphpcode
          mountPath: /var/www/html
          subPath: demophp
          readOnly: true
      volumes:
        - name: gitphpcode
          gitRepo:
            repository: https://github.com/vipin2411/demophp.git

